FROM python:3.12-alpine

WORKDIR /app

COPY pyproject.toml .

RUN pip install uv
RUN uv sync

COPY src src

ENV PYTHONPATH=/app/src

CMD ["uv", "run", "celery", "-A", "bg_tasks.celery_app", "worker", "--concurrency=1", "--loglevel=info"] 