services:
  bot:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src
      - ../alembic:/app/alembic
      - ../alembic.ini:/app/alembic.ini
      - ../logs:/app/logs
    depends_on:
      - redis
      - postgres
      - celery
      - celery-beat
    stdin_open: true
    tty: true

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    env_file:
      - ../.env
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT} --appendonly yes

  postgres:
    image: postgres:17
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  flower:
    build:
      context: ../
      dockerfile: Dockerfile.flower
    volumes:
      - ../src:/app/src
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
      - celery-beat
    env_file:
      - ../.env

  celery:
    build:
      context: ../
      dockerfile: Dockerfile.celery
    env_file:
      - ../.env
    depends_on:
      - redis
      - postgres
    volumes:
      - ../src:/app/src
      - ../logs:/app/logs
    stdin_open: true
    tty: true

  celery-beat:
    build:
      context: ../
      dockerfile: Dockerfile.celery
    command: uv run celery -A bg_tasks.celery_app beat -S redbeat.RedBeatScheduler --loglevel=info
    env_file:
      - ../.env
    depends_on:
      - celery
    volumes:
      - ../src:/app/src
      
volumes:
  redis_data:
  pg_data: