name: Деплой на тест стенд

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Логин в Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker Bot Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/test-${{ secrets.PROJECT_NAME }}:latest
          file: ./Dockerfile
      - name: Build and push Docker Celery Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.celery
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/test-${{ secrets.PROJECT_NAME }}-celery:latest
      
      - name: Деплой на прод сервер
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USERNAME }}
          key: ${{ secrets.TEST_SSH_KEY }}
          script: |
            cd /root/${{secrets.PROJECT_NAME}}
            docker compose --env-file .env -f docker/docker-compose-test.yml down
            git pull
            docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/test-${{ secrets.PROJECT_NAME }}:latest || true
            docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/test-${{ secrets.PROJECT_NAME }}-celery:latest || true
            docker compose --env-file .env -f docker/docker-compose-test.yml pull
            docker compose --env-file .env -f docker/docker-compose-test.yml up -d